### ISSUE TITLE
Allow callback to specify what to use for "this"

### ISSUE THREAD

**Issue by ryandesign** [dperini/ContentLoaded#2]
Thanks for ContentLoaded! It looks like exactly what I'm looking for, as I try to rid a [canvas library I'm developing](http://canviz.org/) from its dependency on Prototype.js.

However, my library is object-oriented, and I want to let my users create objects that can call a callback when the DOM is ready. Basically I want to be able to specify what to bind "this" to when ContentLoaded calls the callback; currently it always binds "this" to the window object that's supplied in the first parameter.

Here's a [simple patch](https://gist.github.com/1694157) that seems to work, along with an example showing how I would be using this feature. Does this seem reasonable to you?

**Comment by dperini** [comment]
The "ContentLoaded()" function was designed to be invoked only once and to notify once that DOMContentLoaded has happened.

It was not tested for registering several DOMContentLoader listeners at the same time (or "setTimeout()" in IE).

I suggest you build a wrapper around "ContentLoaded()" that does exactly what you actually need.

Write a registry method using an Hash object that keeps a list of the callbacks you need (and their scope if necessary) and invoke each callback in a loop when you are notified that "DOMContentLoaded" was fired.

This doesn't means the modification you did doesn't work as is :)

**Comment by lionelB** [comment]
you could add severals callback  if add function currying 

``` javascript
window.domReady = contentloaded.bind(undefined, window);
window.domReady( function( ) {
   console.log("domreayd1");
});
window.domReady( function( ) {
   console.log("domreayd2");
});

}
```
