### ISSUE TITLE
Add bower support for package management?

### ISSUE THREAD

**Issue by sogko** [dperini/ContentLoaded#6]
Hi there,
I realised that I use `contentloaded.js` fairly quite often in my projects.

Have you considered adding the script to bower registry? It would be convenient to simply do a 

```
bower install contentloaded
```

Anyway, thanks a lot for the work!

**Comment by dkleehammer** [comment]
@sogko I've created a bower package for Diego but I used contentloaded2 so he can still use the original for his own project.  I used version 1.2.1 since I switched his file from tab indention to spacing to be more properly used by editors, I created a dist and minified version of the file as well.

To see versions:
`bower info contentloaded2`

To install the package:
`bower install contentloaded2`

**Comment by sogko** [comment]
@dkleehammer that sounds good! I'll just use your bower package till @dperini decides what he wants to do.

Thanks!

**Comment by dkleehammer** [comment]
@sogko I'm having some issues with my jslint setup still for my gulp tasks, but it does run correctly.  I just made version 1.2.2 with some attempt to fix some of it.  In all honesty I should use a task runner to lint and build before publishing it, but let me see what @dperini  is going to do.

**Comment by dperini** [comment]
I added both a minified version of the code and a "bower.json" file to support package management.
Hope this fulfills the request !

**Comment by sogko** [comment]
@dperini that's great! 

I guess the only thing left to do is to tag a releasee and add `ContentLoaded` to bower registry (bower uses gittags for versioning).

Will be looking forward to that!

Thanks for all the work @dperini

**Comment by dperini** [comment]
Thank you for pushing me to support `bower`.
I will apply the same support to other projects I have.
Please verify and tell if I missed something in the TODO list.

**Comment by sogko** [comment]
@dperini Perfect! Thanks again for considering doing this, appreciate all the work and effort you've put into writing `contentloaded.js`.

For future reference for other would-be readers, its registered as `contentloaded`

```
bower install contentloaded
```

**Comment by dkleehammer** [comment]
Perfect, i'll drop contentloaded2 now.  Thanks!

**Comment by dperini** [comment]
Thank you to both for the heads-up and help !
